server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
    loadbalancer:
      ribbon:
        enabled: false

logging:
  level:
    org.springframework.web: DEBUG
